const scheduleData = [
  {
    scheduleId: 1,
    departureDate: "2024-10-10",
    departureTime: "08:00:00",
    capacity: 30,
    booked: 20,
    status: "Open",
    tour: {
      tourId: 1,
      tourName: "Quy Nhơn - Kỳ Co - Eo Gió - Phú Yên",
      duration: 3,
      tourType: "Domestic",
      description: "Explore the beauty of Quy Nhơn and Phú Yên.",
      policyId: 1,
    },
  },
  {
    scheduleId: 2,
    departureDate: "2024-10-15",
    departureTime: "09:00:00",
    capacity: 25,
    booked: 20,
    status: "Closed",
    tour: {
      tourId: 2,
      tourName: "Hà Nội - Hạ Long - Sa Pa",
      duration: 5,
      tourType: "Domestic",
      description: "Experience the scenic landscapes of northern Vietnam.",
      policyId: 2,
    },
  },
  {
    scheduleId: 3,
    departureDate: "2024-10-20",
    departureTime: "07:30:00",
    capacity: 20,
    booked: 8,
    status: "Open",
    tour: {
      tourId: 1,
      tourName: "Quy Nhơn - Kỳ Co - Eo Gió - Phú Yên",
      duration: 3,
      tourType: "Domestic",
      description: "Explore the beauty of Quy Nhơn and Phú Yên.",
      policyId: 1,
    },
  },
  {
    scheduleId: 4,
    departureDate: "2024-11-01",
    departureTime: "10:00:00",
    capacity: 40,
    booked: 35,
    status: "Open",
    tour: {
      tourId: 3,
      tourName: "Đà Lạt - Thành Phố Ngàn Hoa",
      duration: 4,
      tourType: "Domestic",
      description: "Discover the romantic city of Đà Lạt.",
      policyId: 3,
    },
  },
  {
    scheduleId: 5,
    departureDate: "2024-11-10",
    departureTime: "14:00:00",
    capacity: 50,
    booked: 50,
    status: "Full",
    tour: {
      tourId: 4,
      tourName: "Đà Nẵng - Bà Nà Hills - Hội An",
      duration: 4,
      tourType: "Domestic",
      description: "Visit central Vietnam's cultural highlights.",
      policyId: 4,
    },
  },
  {
    scheduleId: 6,
    departureDate: "2024-11-20",
    departureTime: "06:30:00",
    capacity: 30,
    booked: 15,
    status: "Open",
    tour: {
      tourId: 2,
      tourName: "Hà Nội - Hạ Long - Sa Pa",
      duration: 5,
      tourType: "Domestic",
      description: "Experience the scenic landscapes of northern Vietnam.",
      policyId: 2,
    },
  },
  {
    scheduleId: 7,
    departureDate: "2024-12-05",
    departureTime: "12:00:00",
    capacity: 35,
    booked: 30,
    status: "Open",
    tour: {
      tourId: 5,
      tourName: "Phú Quốc - Đảo Ngọc",
      duration: 4,
      tourType: "Domestic",
      description: "Relax in the tropical paradise of Phú Quốc.",
      policyId: 5,
    },
  },
  {
    scheduleId: 8,
    departureDate: "2024-12-15",
    departureTime: "07:00:00",
    capacity: 45,
    booked: 40,
    status: "Open",
    tour: {
      tourId: 6,
      tourName: "Nha Trang - Biển Xanh Cát Trắng",
      duration: 3,
      tourType: "Domestic",
      description:
        "Enjoy the clear waters and vibrant marine life of Nha Trang.",
      policyId: 6,
    },
  },
  {
    scheduleId: 9,
    departureDate: "2025-01-05",
    departureTime: "09:00:00",
    capacity: 20,
    booked: 18,
    status: "Open",
    tour: {
      tourId: 1,
      tourName: "Quy Nhơn - Kỳ Co - Eo Gió - Phú Yên",
      duration: 3,
      tourType: "Domestic",
      description: "Explore the beauty of Quy Nhơn and Phú Yên.",
      policyId: 1,
    },
  },
  {
    scheduleId: 10,
    departureDate: "2025-01-15",
    departureTime: "15:30:00",
    capacity: 25,
    booked: 20,
    status: "Open",
    tour: {
      tourId: 7,
      tourName: "Huế - Thành Phố Cổ Kính",
      duration: 3,
      tourType: "Domestic",
      description: "Delve into the historical charm of Huế.",
      policyId: 7,
    },
  },
];

export const getScheduleData = async () => {
  return new Promise((resolve) => {
    setTimeout(() => resolve(scheduleData), 500);
  });
};
