export const PERMISSIONS = {
    MANAGE_TOUR: 'MANAGE_TOUR',
    MANAGE_BOOKING: 'MANAGE_BOOKING',
    APPROVE_BOOKING_REGISTER: 'APPROVE_BOOKING_REGISTER',
    MANAGE_TOUR_MEDIA: 'MANAGE_TOUR_MEDIA',
    MANAGE_TOUR_PROGRAM: 'MANAGE_TOUR_PROGRAM',
    MANAGE_TOUR_POLICY: 'MANAGE_TOUR_POLICY',
    MANAGE_TOUR_PRICE: 'MANAGE_TOUR_PRICE',
    MANAGE_LOCATION: 'MANAGE_LOCATION',
    MANAGE_EMPLOYEE: 'MANAGE_EMPLOYEE'
  };
  